# fly.toml app configuration file generated for a11y-pdf-audit on 2026-02-16T22:47:37+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'a11y-pdf-audit'
primary_region = 'fra'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "a11y_data"
  destination = "/data"

[env]
  # Wir biegen alle Pfade auf das Volume um
  HF_HOME = "/data/hf_models"
  SURYA_CACHE_DIR = "/data/surya"
  MARKER_CACHE_DIR = "/data/marker"
  # WICHTIG: Deine App muss wissen, wo die Reports hin sollen
  OUTPUT_DIR = "/data/output"
